const langObj = {
  ru: {
    loading: "Загружаем",
    reboot: "Перезагрузка бота",
    pages: {
      main: "Графики",
      fbi: "FBI",
      notes: "Заметки",
      tags: "Теги",
      archive: "Архив",
      calendar: "Календарь",
      settings: "Настройки",
      database: "База данных",
    },
    menu: {
      getTheme: "Тема сайта",
      autoload: "Автозагрузка",
      autoloadcompleted: "Всё загружено",
      filter: {
        name: "Фильтр",
        same: "Общее",
        theme: "Оформление",
        resetAll: "Сброс всех настроек",
        resetAllConfirm: "Подтвердите сброс всех настроек",
        reset: "Сброс",
        resetConfirm: "Подтвердите сброс настроек для страницы",
      },
    },
    settings: {
      activePage: "Активация при заходе на страницу",
      hueRotate: "Кастомизация палитры сайта",
      UTC: "Часовой пояс",
      add: "Добавить",
      delete: "Удалить",
      save: "Сохранить",
      total: "Суммарно",
      streamers: {
        add: "Добавить новый канал",
        names: "Список каналов",
        tracking: "Отслеживание",        
      },
      main: {
        add: "Добавить новую группу",
        groups: "Список групп",
        triggers: "Список триггеров",    
      },
      fbi: {
        add: "Добавить новое отслеживание",
        names: "Список отслеживаемого",
      },
    },
    time: {
      online: "онлайн",
      today: "сегодня",
      yesterday: "вчера",
      month: {
        m0: "января",
        m1: "февраля",
        m2: "марта",
        m3: "апреля",
        m4: "мая",
        m5: "июня",
        m6: "июля",
        m7: "августа",
        m8: "сентября",
        m9: "октября",
        m10: "ноября",
        m11: "декабря",
      }
    },
  },  
  en: {
    loading: "Loading",
    reboot: "Bot reboot",
    pages: {
      main: "Main",
      fbi: "FBI",
      notes: "Notes",
      tags: "Tags",
      archive: "Archive",
      calendar: "Calendar",
      settings: "Settings",
      database: "Database",
    },
    menu: {
      getTheme: "Site Theme",
      autoload: "Autoload",
      autoloadcompleted: "All uploaded",
      filter: {
        name: "Filter",
        same: "Same",
        theme: "Decor",
        resetAll: "Reset all settings",
        resetAllConfirm: "Confirm reset all settings",
        reset: "Reset",
        resetConfirm: "Confirm reset for page",
      },
    },
    settings: {
      activePage: "Activation when entering the page", 
      UTC: "Timezone",
      add: "Add",
      delete: "Delete",
      save: "Save",
      total: "Total",
      theme: {
        title: "Site palette customization",
      },
      streamers: {
        add: "Add new channel", 
        title: "Channel list", 
        subtitle: "Tracking",
      },
      main: {
        add: "Add new group",
        title: "Group list",
        subtitle: "Trigger list",    
      },
      fbi: {
        add: "Add new tracking",
        title: "Track List",
      },
    },
    time: {
      online: "online",
      today: "today",
      yesterday: "yesterday",
      month: {
        m0: "January",
        m1: "February",
        m2: "March",
        m3: "April",
        m4: "May",
        m5: "June",
        m6: "July",
        m7: "August",
        m8: "September",
        m9: "October",
        m10: "November",
        m11: "December",
      }
    },
  },    
}; 
